#!/bin/bash

echo "==================================================="
echo "DOCKER HUB CREDENTIALS SETUP VERIFICATION"
echo "==================================================="
echo ""

echo "1. JENKINS CREDENTIALS SETUP"
echo "   Go to: http://localhost:8080/credentials/"
echo "   Click: System → Global credentials (unrestricted) → Add Credentials"
echo ""
echo "   Configuration:"
echo "   - Kind: Username with password"
echo "   - Username: hitendra369"
echo "   - Password: [Your Docker Hub Access Token]"
echo "   - ID: docker_hub_creds"
echo "   - Description: Docker Hub Credentials"
echo ""

echo "2. DOCKER HUB ACCESS TOKEN"
echo "   If you don't have an access token:"
echo "   - Go to: https://hub.docker.com/settings/security"
echo "   - Click: New Access Token"
echo "   - Name: jenkins-ci"
echo "   - Permissions: Read, Write, Delete"
echo "   - Copy the generated token"
echo ""

echo "3. VERIFY REPOSITORY EXISTS"
echo "   Make sure this repository exists on Docker Hub:"
echo "   https://hub.docker.com/r/hitendra369/laravel_dynamic_dashboard"
echo ""
echo "   If it doesn't exist, create it:"
echo "   - Go to: https://hub.docker.com/repositories"
echo "   - Click: Create Repository"
echo "   - Name: laravel_dynamic_dashboard"
echo "   - Visibility: Public (or Private if you prefer)"
echo ""

echo "4. TEST DOCKER LOGIN MANUALLY"
echo "   You can test Docker login from the Jenkins container:"
echo "   docker exec -it jenkins-server bash"
echo "   docker login -u hitendra369"
echo ""

echo "5. JENKINSFILE FIXES APPLIED"
echo "   ✅ Fixed insecure Groovy string interpolation"
echo "   ✅ Corrected Docker registry URL"
echo "   ✅ Removed redundant registry prefix in push commands"
echo ""

echo "==================================================="
echo "Next: Trigger a new build in Jenkins to test the fixes!"
echo "==================================================="