version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-server
    ports:
      - "8080:8080"     # Jenkins web interface
      - "50000:50000"   # Jenkins agent port
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Jenkins to use Docker
      - .:/workspace    # Mount current project directory
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true
    user: root          # Required for Docker socket access
    restart: unless-stopped

volumes:
  jenkins_home:
    driver: local