#!/bin/bash

echo "==================================================="
echo "STEP-BY-STEP: SETTING UP RENDER CREDENTIALS IN JENKINS"
echo "==================================================="
echo ""

echo "🔑 STEP 1: GET RENDER API KEY"
echo "==================================================="
echo ""
echo "1. Go to Render Account Settings:"
echo "   https://dashboard.render.com/account"
echo ""
echo "2. Scroll down to 'API Keys' section"
echo ""
echo "3. Click 'Create API Key'"
echo ""
echo "4. Set Name: jenkins-deployment"
echo ""
echo "5. Copy the generated API key (starts with 'rnd_')"
echo ""

echo "🔧 STEP 2: ADD API KEY TO JENKINS"
echo "==================================================="
echo ""
echo "1. Open Jenkins Dashboard:"
echo "   http://localhost:8080"
echo ""
echo "2. Go to: Manage Jenkins → Manage Credentials"
echo ""
echo "3. Click: System → Global credentials (unrestricted)"
echo ""
echo "4. Click: Add Credentials"
echo ""
echo "5. Configure as follows:"
echo "   - Kind: Secret text"
echo "   - Secret: [Paste your Render API key here]"
echo "   - ID: render_api_key"
echo "   - Description: Render API Key for Deployment"
echo ""
echo "6. Click: OK"
echo ""

echo "🌐 STEP 3: CREATE RENDER WEB SERVICE & GET SERVICE ID"
echo "==================================================="
echo ""
echo "1. Go to Render Dashboard:"
echo "   https://dashboard.render.com/"
echo ""
echo "2. Click: New + → Web Service"
echo ""
echo "3. Choose: Deploy an existing image from a registry"
echo ""
echo "4. Configure:"
echo "   - Image URL: hitendra369/laravel_dynamic_dashboard:latest"
echo "   - Service Name: laravel-dynamic-dashboard"
echo "   - Region: oregon (or your preferred region)"
echo "   - Instance Type: Free (or paid plan)"
echo ""
echo "5. After creation, copy the Service ID from URL:"
echo "   https://dashboard.render.com/web/srv-XXXXXXXXXXXXXX"
echo "   (Copy the 'srv-XXXXXXXXXXXXXX' part)"
echo ""

echo "✏️  STEP 4: UPDATE JENKINSFILE WITH SERVICE ID"
echo "==================================================="
echo ""
echo "Replace line 10 in Jenkinsfile:"
echo "FROM: RENDER_SERVICE_ID = 'your-render-service-id'"
echo "TO:   RENDER_SERVICE_ID = 'srv-XXXXXXXXXXXXXX'"
echo ""
echo "Then commit and push the change to GitHub"
echo ""

echo "🚀 STEP 5: TEST THE PIPELINE"
echo "==================================================="
echo ""
echo "1. Make a small change in your code"
echo "2. Commit and push to main branch"
echo "3. Watch Jenkins automatically:"
echo "   - Build Docker image"
echo "   - Push to Docker Hub"
echo "   - Deploy to Render"
echo "   - Your app goes live!"
echo ""

echo "==================================================="
echo "QUICK LINKS:"
echo "==================================================="
echo "Jenkins Dashboard: http://localhost:8080"
echo "Jenkins Credentials: http://localhost:8080/credentials/"
echo "Render Dashboard: https://dashboard.render.com/"
echo "Render Account Settings: https://dashboard.render.com/account"
echo ""