#!/bin/bash

echo "==================================================="
echo "RENDER DEPLOYMENT SETUP HELPER"
echo "==================================================="
echo ""

echo "📋 CHECKLIST - Complete these steps:"
echo ""
echo "1. ✅ Create Render Web Service"
echo "   - Go to: https://dashboard.render.com/"
echo "   - Click: New + → Web Service"
echo "   - Choose: Deploy an existing image from a registry"
echo "   - Image URL: hitendra369/laravel_dynamic_dashboard:latest"
echo ""

echo "2. ✅ Get your Render Service ID"
echo "   - After creating service, copy the Service ID from URL"
echo "   - Format: srv-XXXXXXXXXXXXXX"
echo "   - Update Jenkinsfile: Replace 'your-render-service-id' with your actual ID"
echo ""

echo "3. ✅ Create Render API Key"
echo "   - Go to: https://dashboard.render.com/account"
echo "   - Create API Key with name: jenkins-deployment"
echo "   - Copy the generated key"
echo ""

echo "4. ✅ Add API Key to Jenkins"
echo "   - Go to: http://localhost:8080/credentials/"
echo "   - Add Credentials → Secret text"
echo "   - ID: render_api_key"
echo "   - Secret: [Your Render API Key]"
echo ""

echo "5. ✅ Configure Environment Variables in Render"
echo "   - Add all necessary Laravel environment variables"
echo "   - Set APP_ENV=production"
echo "   - Set APP_DEBUG=false"
echo "   - Configure database connection"
echo ""

echo "==================================================="
echo "UPDATED PIPELINE STAGES:"
echo "==================================================="
echo ""
echo "1. Checkout code from GitHub"
echo "2. Build Docker image with build number tag"
echo "3. Login to Docker Hub"
echo "4. Push Docker image (both versioned and 'latest' tags)"
echo "5. 🆕 Deploy to Render (NEW STAGE)"
echo "6. Clean up local Docker images"
echo ""

echo "==================================================="
echo "NEXT STEPS:"
echo "==================================================="
echo ""
echo "1. Complete the Render setup using RENDER_DEPLOYMENT.md guide"
echo "2. Update the Service ID in Jenkinsfile"
echo "3. Add Render API key to Jenkins credentials"
echo "4. Commit and push the updated Jenkinsfile"
echo "5. Test the complete CI/CD pipeline"
echo ""

echo "Once setup is complete, your app will auto-deploy to Render on every push! 🚀"
echo ""